// @Library('slack-shared-lib') _

pipeline {
    agent {
        label {
            label "SlaveNode"
        }
    }
    stages {
 
        stage('Installing Reqirements') {

            steps {
                //sh cdk
                sh 'sudo pip3 install -r requirements.txt' 
            
              }
        }
        stage( 'Running App' ){

            steps{
                sh '''#!/bin/bash
                        echo "Runnig py app"
                        chmod +x script.sh
                        ./script.sh
                    '''
            }
        }              
            }

    // post {
    //     always{
    //         // calling shared Lib 
    //         slack()                       
    //     }
    // }

}
