jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "pass"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
# security:
#   queueItemAuthenticator:
#     authenticators:
#     - global:
#         strategy: "triggeringUsersAuthorizationStrategy"
unclassified:
  location:
    url: http://127.0.0.1:8080/
jobs:
- file: /var/jenkins_home/jobdsl.groovy
