// @Library('slack-shared-lib') _

pipeline {
    agent {
        label {
            label "testSlaveNode"
        }
    }
    stages {
        stage('Copying files') {
            steps {
                //sh cdk
                sh '''#!/bin/bash
                        chmod +x copy.sh
                        ./copy.sh
                    ''' 
            
              }
        }
        stage( 'Deploying App' ){

            steps{
                sh '''#!/bin/bash
                        echo "Runnig py app"
                        chmod +x script.sh
                        ./script.sh
                    '''
            }
        }              
}

    // post {
    //     always{
    //         // calling shared Lib 
    //         slack()                       
    //     }
    // }

}
